'use client';
import { useState, useEffect } from 'react';
import styles from './page.module.css';

export default function AnalyticsPage() {
    const [floodRisk, setFloodRisk] = useState(null);
    const [historical, setHistorical] = useState(null);
    const [alerts, setAlerts] = useState(null);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        Promise.all([
            fetch('/api/flood-risk').then(r => r.ok ? r.json() : null),
            fetch('/api/historical?months=3').then(r => r.ok ? r.json() : null),
            fetch('/api/alerts').then(r => r.ok ? r.json() : null),
        ]).then(([risk, hist, al]) => {
            setFloodRisk(risk);
            setHistorical(hist);
            setAlerts(al);
        }).catch(() => { }).finally(() => setLoading(false));
    }, []);

    const monthlyData = historical?.monthlyAggregates || [];
    const maxRainfall = Math.max(...monthlyData.map(m => m.totalPrecip), 1);

    const getRiskColor = (score) => {
        if (score >= 75) return 'var(--accent-red)';
        if (score >= 50) return 'var(--accent-orange)';
        if (score >= 25) return 'var(--accent-amber)';
        return 'var(--accent-green)';
    };

    // Zone risk rankings from live flood risk API
    const zoneRankings = (floodRisk?.zones || [])
        .map(z => ({ zone: z.name, score: z.riskScore, level: z.riskLevel }))
        .sort((a, b) => b.score - a.score);

    return (
        <div style={{ animation: 'fadeIn 0.35s var(--ease-out)' }}>
            <div className="page-header">
                <h1>Analytics</h1>
                <p>Real-time flood risk analysis and historical weather patterns</p>
            </div>

            {/* Summary Stats - all from real data */}
            <div className="stats-grid animate-stagger">
                <div className="stat-card" style={{ '--accent-color': 'var(--accent-blue)' }}>
                    <div className="stat-icon" style={{ background: 'var(--accent-blue-muted)', color: 'var(--accent-blue)' }}>
                        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M12 2.69l5.66 5.66a8 8 0 1 1-11.31 0z" /></svg>
                    </div>
                    <div className="stat-info">
                        <div className="stat-label">Total Rainfall</div>
                        <div className="stat-value">{historical?.totalRainfall ?? '—'}mm</div>
                        <div className="stat-change" style={{ color: 'var(--text-muted)' }}>
                            Past {historical?.period?.totalDays ?? '—'} days
                        </div>
                    </div>
                </div>
                <div className="stat-card" style={{ '--accent-color': 'var(--accent-red)' }}>
                    <div className="stat-icon" style={{ background: 'var(--accent-red-muted)', color: 'var(--accent-red)' }}>
                        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z" /></svg>
                    </div>
                    <div className="stat-info">
                        <div className="stat-label">Heavy Rain Days</div>
                        <div className="stat-value">{historical?.heavyRainDays ?? '—'}</div>
                        <div className="stat-change" style={{ color: 'var(--text-muted)' }}>
                            &gt;20mm/day
                        </div>
                    </div>
                </div>
                <div className="stat-card" style={{ '--accent-color': 'var(--accent-amber)' }}>
                    <div className="stat-icon" style={{ background: 'var(--accent-amber-muted)', color: 'var(--accent-amber)' }}>
                        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9" /><path d="M10.3 21a1.94 1.94 0 0 0 3.4 0" /></svg>
                    </div>
                    <div className="stat-info">
                        <div className="stat-label">Active Alerts</div>
                        <div className="stat-value">{alerts?.active ?? 0}</div>
                        <div className="stat-change" style={{ color: 'var(--text-muted)' }}>
                            {alerts?.total ?? 0} total · {alerts?.autoGenerated ?? 0} auto
                        </div>
                    </div>
                </div>
                <div className="stat-card" style={{ '--accent-color': 'var(--accent-green)' }}>
                    <div className="stat-icon" style={{ background: 'var(--accent-green-muted)', color: 'var(--accent-green)' }}>
                        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M22 12h-4l-3 9L9 3l-3 9H2" /></svg>
                    </div>
                    <div className="stat-info">
                        <div className="stat-label">Current Risk</div>
                        <div className="stat-value" style={{ color: getRiskColor(floodRisk?.overallRiskScore ?? 0) }}>
                            {floodRisk?.overallRiskLevel ?? '—'}
                        </div>
                        <div className="stat-change" style={{ color: 'var(--text-muted)' }}>
                            Score: {floodRisk?.overallRiskScore ?? '—'}/100
                        </div>
                    </div>
                </div>
            </div>

            <div className="grid-2">
                {/* Monthly Rainfall Chart — real data from Open-Meteo */}
                <div className="card">
                    <h3 className="section-title" style={{ marginBottom: 'var(--sp-4)' }}>Rainfall by month · real data</h3>
                    {monthlyData.length > 0 ? (
                        <>
                            <div className={styles.monthlyChart}>
                                {monthlyData.map((m, i) => (
                                    <div key={i} className={styles.monthCol}>
                                        <div className={styles.monthBars}>
                                            <div
                                                className={styles.rainfallBar}
                                                style={{ height: `${(m.totalPrecip / maxRainfall) * 100}%` }}
                                                title={`${m.monthLabel}: ${m.totalPrecip}mm total, ${m.rainyDays} rainy days`}
                                            />
                                            {m.heavyDays > 0 && (
                                                <div className={styles.floodDot} title={`${m.heavyDays} heavy rain days (>20mm)`}>
                                                    {m.heavyDays}
                                                </div>
                                            )}
                                        </div>
                                        <span className={styles.monthLabel}>{m.monthLabel}</span>
                                    </div>
                                ))}
                            </div>
                            <div className={styles.chartLegend}>
                                <span><span className={styles.legendBar} style={{ background: 'var(--brand)' }}></span> Monthly total (mm)</span>
                                <span><span className={styles.legendDot} style={{ background: 'var(--accent-red)' }}></span> Heavy rain days</span>
                            </div>
                        </>
                    ) : (
                        <div style={{ textAlign: 'center', padding: 'var(--sp-10)', color: 'var(--text-muted)', fontSize: '0.84rem' }}>
                            {loading ? 'Fetching historical data…' : 'No historical data available'}
                        </div>
                    )}
                </div>

                {/* Zone Risk Rankings — from live flood risk API */}
                <div className="card">
                    <h3 className="section-title" style={{ marginBottom: 'var(--sp-4)' }}>Zone risk · live</h3>
                    <div className={styles.zoneList}>
                        {zoneRankings.length > 0 ? zoneRankings.map((zone, i) => (
                            <div key={zone.zone} className={styles.zoneItem} style={{ animation: `slideInRight 0.4s var(--ease-out) ${i * 60}ms both` }}>
                                <span className={styles.zoneRank}>#{i + 1}</span>
                                <span className={styles.zoneName}>{zone.zone}</span>
                                <div className={styles.zoneBar}>
                                    <div className={styles.zoneBarFill} style={{ width: `${zone.score}%`, background: getRiskColor(zone.score) }} />
                                </div>
                                <span className={styles.zoneScore} style={{ color: getRiskColor(zone.score) }}>{zone.score}</span>
                                <span className={`badge badge-${zone.level.toLowerCase()}`} style={{ fontSize: '0.6rem', padding: '1px 6px' }}>{zone.level}</span>
                            </div>
                        )) : (
                            <div style={{ textAlign: 'center', padding: 'var(--sp-10)', color: 'var(--text-muted)', fontSize: '0.84rem' }}>
                                {loading ? 'Loading zone data…' : 'No zone data available'}
                            </div>
                        )}
                    </div>
                </div>
            </div>

            {/* Current conditions summary */}
            <div className="card" style={{ marginTop: 'var(--sp-6)' }}>
                <h3 className="section-title" style={{ marginBottom: 'var(--sp-4)' }}>Current conditions</h3>
                <div className="table-container" style={{ border: 'none', background: 'transparent' }}>
                    <table className="data-table">
                        <thead>
                            <tr>
                                <th>Metric</th>
                                <th>Value</th>
                                <th>Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td style={{ fontWeight: 600 }}>Current Rainfall</td>
                                <td>{floodRisk?.currentRainfall ?? '—'} mm/hr</td>
                                <td>
                                    <span className={`badge ${(floodRisk?.currentRainfall ?? 0) > 34.5 ? 'badge-critical' : (floodRisk?.currentRainfall ?? 0) > 15 ? 'badge-high' : (floodRisk?.currentRainfall ?? 0) > 5 ? 'badge-moderate' : 'badge-low'}`}>
                                        {(floodRisk?.currentRainfall ?? 0) > 34.5 ? 'CRITICAL' : (floodRisk?.currentRainfall ?? 0) > 15 ? 'HIGH' : (floodRisk?.currentRainfall ?? 0) > 5 ? 'MODERATE' : 'NORMAL'}
                                    </span>
                                </td>
                            </tr>
                            <tr>
                                <td style={{ fontWeight: 600 }}>5-Day Cumulative</td>
                                <td>{floodRisk?.antecedent5Day ?? '—'} mm</td>
                                <td>
                                    <span className={`badge ${(floodRisk?.antecedent5Day ?? 0) > 50 ? 'badge-high' : 'badge-low'}`}>
                                        {(floodRisk?.antecedent5Day ?? 0) > 50 ? 'SATURATED' : 'NORMAL'}
                                    </span>
                                </td>
                            </tr>
                            <tr>
                                <td style={{ fontWeight: 600 }}>Soil Moisture</td>
                                <td>{((floodRisk?.soilMoisture ?? 0) * 100).toFixed(0)}%</td>
                                <td>
                                    <span className={`badge ${(floodRisk?.soilMoisture ?? 0) > 0.7 ? 'badge-high' : 'badge-low'}`}>
                                        {(floodRisk?.soilMoisture ?? 0) > 0.7 ? 'WET' : 'OKAY'}
                                    </span>
                                </td>
                            </tr>
                            <tr>
                                <td style={{ fontWeight: 600 }}>Overall Risk Score</td>
                                <td>{floodRisk?.overallRiskScore ?? '—'}/100</td>
                                <td>
                                    <span className={`badge badge-${(floodRisk?.overallRiskLevel ?? 'LOW').toLowerCase()}`}>
                                        {floodRisk?.overallRiskLevel ?? '—'}
                                    </span>
                                </td>
                            </tr>
                            <tr>
                                <td style={{ fontWeight: 600 }}>Rainy Days (period)</td>
                                <td>{historical?.rainyDays ?? '—'} of {historical?.period?.totalDays ?? '—'}</td>
                                <td>
                                    <span className="badge badge-info">
                                        {historical?.rainyDays && historical?.period?.totalDays
                                            ? `${((historical.rainyDays / historical.period.totalDays) * 100).toFixed(0)}%`
                                            : '—'}
                                    </span>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div style={{ marginTop: 'var(--sp-3)', fontSize: '0.68rem', color: 'var(--text-faint)' }}>
                    Data from Open-Meteo API · Last updated: {floodRisk?.timestamp ? new Date(floodRisk.timestamp).toLocaleString('en-KE') : '—'}
                </div>
            </div>
        </div>
    );
}
