// Alerts API - Generates alerts dynamically from real weather data
import { NextResponse } from 'next/server';

// Only user-created alerts are stored here (no fake data)
let userAlerts = [];

// Generate alerts dynamically based on real weather/flood conditions
async function generateWeatherAlerts() {
    const dynamicAlerts = [];

    try {
        // Fetch real flood risk data
        const riskRes = await fetch(`${process.env.NEXT_PUBLIC_BASE_URL || 'http://localhost:3000'}/api/flood-risk`);
        let riskData = null;

        if (riskRes.ok) {
            riskData = await riskRes.json();
        }

        if (!riskData?.zones) return dynamicAlerts;

        const now = new Date();

        // Generate alerts for zones that actually have elevated risk
        for (const zone of riskData.zones) {
            if (zone.riskLevel === 'CRITICAL') {
                dynamicAlerts.push({
                    id: `auto-critical-${zone.name}`,
                    severity: 'EMERGENCY',
                    title: `Flash Flood Warning - ${zone.name}`,
                    message: `High flood risk detected in ${zone.name}. Current rainfall: ${riskData.currentRainfall}mm/hr. Risk score: ${zone.riskScore}/100. Take precautions and avoid low-lying areas.`,
                    location: `${zone.name}, Nairobi`,
                    coordinates: { lat: zone.lat, lng: zone.lng },
                    channels: ['SMS', 'WHATSAPP', 'TELEGRAM', 'USSD'],
                    status: 'ACTIVE',
                    affectedPopulation: 0,
                    createdAt: now.toISOString(),
                    updatedAt: now.toISOString(),
                    autoGenerated: true,
                });
            } else if (zone.riskLevel === 'HIGH') {
                dynamicAlerts.push({
                    id: `auto-high-${zone.name}`,
                    severity: 'WARNING',
                    title: `Flood Watch - ${zone.name}`,
                    message: `Elevated flood risk in ${zone.name}. Risk score: ${zone.riskScore}/100. Current rainfall: ${riskData.currentRainfall}mm/hr. Monitor conditions and prepare for possible evacuation.`,
                    location: `${zone.name}, Nairobi`,
                    coordinates: { lat: zone.lat, lng: zone.lng },
                    channels: ['SMS', 'TELEGRAM'],
                    status: 'ACTIVE',
                    affectedPopulation: 0,
                    createdAt: now.toISOString(),
                    updatedAt: now.toISOString(),
                    autoGenerated: true,
                });
            } else if (zone.riskLevel === 'MODERATE' && riskData.currentRainfall > 5) {
                dynamicAlerts.push({
                    id: `auto-mod-${zone.name}`,
                    severity: 'WATCH',
                    title: `Rainfall Advisory - ${zone.name}`,
                    message: `Moderate flood risk in ${zone.name}. Current rainfall: ${riskData.currentRainfall}mm/hr. Risk score: ${zone.riskScore}/100. Stay alert.`,
                    location: `${zone.name}, Nairobi`,
                    coordinates: { lat: zone.lat, lng: zone.lng },
                    channels: ['SMS'],
                    status: 'ACTIVE',
                    affectedPopulation: 0,
                    createdAt: now.toISOString(),
                    updatedAt: now.toISOString(),
                    autoGenerated: true,
                });
            }
        }

        // Add a general rainfall info alert if it's currently raining
        if (riskData.currentRainfall > 0) {
            dynamicAlerts.push({
                id: `auto-rain-general`,
                severity: 'INFO',
                title: `Active Rainfall - Nairobi`,
                message: `Rainfall detected across Nairobi at ${riskData.currentRainfall}mm/hr. 5-day cumulative: ${riskData.antecedent5Day}mm. Overall risk: ${riskData.overallRiskLevel}.`,
                location: 'Nairobi, Kenya',
                coordinates: { lat: -1.2921, lng: 36.8219 },
                channels: ['TELEGRAM'],
                status: 'ACTIVE',
                affectedPopulation: 0,
                createdAt: now.toISOString(),
                updatedAt: now.toISOString(),
                autoGenerated: true,
            });
        }
    } catch (e) {
        console.warn('Could not generate weather-based alerts:', e.message);
    }

    return dynamicAlerts;
}

export async function GET() {
    // Combine auto-generated weather alerts with user-created alerts
    const weatherAlerts = await generateWeatherAlerts();
    const allAlerts = [...userAlerts, ...weatherAlerts];

    return NextResponse.json({
        alerts: allAlerts,
        total: allAlerts.length,
        active: allAlerts.filter(a => a.status === 'ACTIVE').length,
        autoGenerated: weatherAlerts.length,
        userCreated: userAlerts.length,
        timestamp: new Date().toISOString(),
    });
}

export async function POST(request) {
    try {
        const body = await request.json();

        const newAlert = {
            id: String(Date.now()),
            severity: body.severity || 'INFO',
            title: body.title,
            message: body.message,
            location: body.location,
            coordinates: body.coordinates || { lat: -1.2921, lng: 36.8219 },
            channels: body.channels || ['SMS'],
            status: 'ACTIVE',
            affectedPopulation: body.affectedPopulation || 0,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
            autoGenerated: false,
        };

        userAlerts.unshift(newAlert);

        return NextResponse.json({
            success: true,
            alert: newAlert,
            dissemination: {
                sms: body.channels?.includes('SMS') ? { status: 'QUEUED', recipients: newAlert.affectedPopulation } : null,
                whatsapp: body.channels?.includes('WHATSAPP') ? { status: 'QUEUED', recipients: Math.floor(newAlert.affectedPopulation * 0.6) } : null,
                telegram: body.channels?.includes('TELEGRAM') ? { status: 'SENT', channel: '@Nairobi_Flood_Alerts' } : null,
                ussd: body.channels?.includes('USSD') ? { status: 'READY', code: '*483*123#' } : null,
            },
        }, { status: 201 });
    } catch (error) {
        return NextResponse.json(
            { error: 'Failed to create alert', message: error.message },
            { status: 400 }
        );
    }
}
